# -*- mode: ruby -*-
# vi: set ft=ruby :

ip="192.168.50.4"

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"

  config.vm.network "private_network", ip: "#{ip}"

  # Install Puppet
  config.vm.provision "shell"  do |shell|
    shell.inline = "
sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
sudo yum install -y puppet
sudo cp /vagrant/repo/nginx.repo /etc/yum.repos.d/
"
  end

  # Run Puppet Script
  config.vm.provision "puppet"  do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file = "default.pp"
  end

  # Tell the user what to do
  config.vm.provision "shell"  do |shell|
    shell.inline = "echo Complete! Bring your browser up and go to #{ip}"
  end
end
