# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.host_name = "my-host"
end
