# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"
  config.vm.network "private_network", ip: "192.168.50.4"
  #config.vm.network "public_network"
  #config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.host_name = "my-host"
end
