# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"

  ##########################################################################################
  ##########################################################################################
  # Client Machine
  ##########################################################################################
  ##########################################################################################
  config.vm.define "client" do |db|
    db.vm.network "private_network", ip: "192.168.50.69"
    db.vm.hostname = "clienthost"
  end

  ##########################################################################################
  ##########################################################################################
  # Load Balancing web server
  ##########################################################################################
  ##########################################################################################
  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.50.60"
    web.vm.hostname = "webhost"

    # Install Puppet
    config.vm.provision "shell"  do |shell|
      shell.inline = "
sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
sudo yum install -y puppet
"
    end

    # Install nginx
    web.vm.provision "puppet"  do |puppet|
      puppet.manifests_path = "web/puppet"
      puppet.manifest_file = "web.pp"
    end
  end

  ##########################################################################################
  ##########################################################################################
  # Ping Service
  ##########################################################################################
  ##########################################################################################

  $script = <<SCRIPT
curl -sL https://rpm.nodesource.com/setup | sudo bash -
sudo yum install -y nodejs
sudo cp /vagrant/service/systemd/ping.service /etc/systemd/system/
sudo cp /vagrant/service/nodejs/*.* /home/vagrant/
sudo systemctl enable ping
sudo systemctl start ping
SCRIPT

  ##########################################################################################
  # Ping Service 1
  ##########################################################################################
  config.vm.define "svc1" do |db|
    db.vm.network "private_network", ip: "192.168.50.61"
    db.vm.hostname = "svchost1"

    # Install nodejs
    config.vm.provision "shell", inline: $script
  end

  ##########################################################################################
  # Ping Service 2
  ##########################################################################################
  config.vm.define "svc2" do |db|
    db.vm.network "private_network", ip: "192.168.50.62"
    db.vm.hostname = "svchost2"

    # Install nodejs
    config.vm.provision "shell", inline: $script
  end

  ##########################################################################################
  # Ping Service 3
  ##########################################################################################
  config.vm.define "svc3" do |db|
    db.vm.network "private_network", ip: "192.168.50.63"
    db.vm.hostname = "svchost3"

    # Install nodejs
    config.vm.provision "shell", inline: $script
  end
end
