# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"

  config.vm.provision "shell"  do |shell|
    shell.inline = "echo Outer Script 1"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.50"
    client.vm.hostname = "clienthost"

    client.vm.provision "shell"  do |shell|
        shell.inline = "echo Client Script"
    end
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.51"
    server.vm.hostname = "serverhost"

    server.vm.provision "shell"  do |shell|
      shell.inline = "echo Server Script"
    end
  end

  config.vm.provision "shell"  do |shell|
    shell.inline = "echo Outer Script 2"
  end
end
