# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"

  # Install Puppet
  config.vm.provision "shell"  do |shell|
    shell.inline = "
sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
sudo yum install -y puppet
"
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.50.6"
    web.vm.hostname = "webhost"

    # Run Puppet Script
    web.vm.provision "puppet"  do |puppet|
      puppet.manifests_path = "puppet"
      puppet.manifest_file = "web.pp"
    end
  end

  config.vm.define "db" do |db|
    db.vm.network "private_network", ip: "192.168.50.7"
    db.vm.hostname = "dbhost"

    # Run Puppet Script
    db.vm.provision "puppet"  do |puppet|
      puppet.manifests_path = "puppet"
      puppet.manifest_file = "db.pp"
    end
  end
end
